services:
  go-app:
    build:
      context: ./.
      dockerfile: Dockerfile
    container_name: go-app-ys4kwkw-124018503803
    volumes:
      - '/data/coolify/applications/ys4kwkw:/go/src/app'
    ports:
      - '7070:7070'
    networks:
      app-network: null
      ys4kwkw: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.297
      - coolify.applicationId=3
      - coolify.type=application
      - coolify.name=go-app-ys4kwkw-124018503803
      - coolify.pullRequestId=0
    restart: unless-stopped
volumes: {  }
networks:
  app-network: null
  ys4kwkw:
    name: ys4kwkw
    external: true
