version: '3.8'

services:
  go-app:
    build:
      context: ./.
      dockerfile: Dockerfile
    container_name: go_app
    volumes:
      - .:/app
    ports:
      - "7070:7070"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
