version: '3.8'

services:
  go-app:
    build:
      context: ./.
      dockerfile: Dockerfile
      args:
        PORT: ${PORT:-7070}  # Default to 7070 if not specified
    container_name: go_app
    volumes:
      - .:/app
    ports:
      - "${PORT:-7070}:${PORT:-7070}"
    environment:
      - PORT=${PORT:-7070}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
