version: '3.8'
services:
  go-app:
    build: ./.
    container_name: go_app
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - nginx
    

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
