# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    # Runs at the top of every hour
    - cron: '0 * * * *'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
  
    - name: Set up ffmpeg
      run:  sudo apt update && sudo apt-get install ffmpeg 

    - name: Set up lux
      run:  go install github.com/iawia002/lux@latest

    - name: Build
      run: go build -v ./...

      #name: Test
      #run: go test -v ./...
